### PR TITLE
:gift_heart: Handover of magetasks to Knative project

### LINKED ISSUE #338: Mage tasks should be under Knative control
Kn-event is using the [github.com/wavesoftware/go-magetasks](https://pkg.go.dev/github.com/wavesoftware/go-magetasks) package as a skeleton for the build.

As it is quite a substantial part of the project, and because of this, it would be a good idea that it would be under the control of the Knative community.

### PR DESCRIPTION
**Pull request by cardil**
**Which issue(s) this PR fixes**:<br>

Fixes knative-extensions/kn-plugin-event#338

## Changes

 - :gift_heart: Handover of magetasks to Knative project

/kind enhancement

### CODE REVIEW

**Comment by cardil** [comment]
/hold

To be tested against kn-plugin-event

**Comment by cardil** [comment]
/cc @dsimansk 

It work with kn-event, as seen in knative-extensions/kn-plugin-event#345

/unhold

**Comment by dsimansk** [comment]
/approve
/lgtm

Adding hold for Productivity WG, @upodroid to check. Or it that's already discussed, @cardil feel free to unhold.
/hold

**Review by upodroid — APPROVED** [review]
We spoke about this yesterday. +1
/hold cancel

**Pull request merged**
