### PR TITLE
Extract tools from test-infra

### PR DESCRIPTION
**Pull request by cardil**
**Which issue(s) this PR fixes**:<br>
Related to https://github.com/knative/community/issues/1291
Companion of https://github.com/knative/test-infra/pull/3773

### CODE REVIEW

**Comment by krsna-m** [comment]
/lgtm
You got some test fails

**Comment by cardil** [comment]
https://github.com/knative/test-infra/pull/3772 should configure prow jobs for this repo

**Review by upodroid — APPROVED** [review]
LGTM

Can you update the prow-tests image to build binaries from this repo?

**Comment by cardil** [comment]
@upodroid:

> _Can you update the prow-tests image to build binaries from this repo?_

I did that already in https://github.com/knative/test-infra/pull/3773

**Comment by cardil** [comment]
@upodroid see: https://github.com/knative/test-infra/pull/3773#issuecomment-1485404209

**Pull request merged**
