### PR TITLE
Bump to golang 1.21 and golang.org/x/mod v0.14.0

### LINKED ISSUE #24: buoy fails with go 1.21 `toolchain` directive
# Problem description
buoy fails with go 1.21 when the `toolchain` directive is in go.mod:

```
cat go.mod | head -n 10
module knative.dev/pkg

go 1.21

toolchain go1.21.6
```

```
buoy needs go.mod --domain knative.dev
Error: go.mod:5: unknown directive: toolchain
Usage:
  buoy needs go.mod [flags]

Flags:
  -d, --domain string   domain filter (i.e. knative.dev) [required]
  -h, --help            help for needs

2024/01/24 10:56:11 Error during command execution: go.mod:5: unknown directive: toolchain
```

### PR DESCRIPTION
**Pull request by ReToCode**
# Context
- Bump to golang 1.21 and golang.org/x/mod v0.14.0

Fixes #24

/lint

/assign @skonto

### CODE REVIEW

**Comment by ReToCode** [comment]
/override "style / Golang / Auto-format and Check"

**Comment by ReToCode** [comment]
PTAL, discussion [here](https://cloud-native.slack.com/archives/C04LY4Y3EHF/p1706094072418189?thread_ts=1706086464.468139&cid=C04LY4Y3EHF)

/assign @cardil
/assign @kvmware
/assign @psschwei
/assign @upodroid

Also this repo seems to be outdated with GH action sync and peribolos sync.

**Comment by dsimansk** [comment]
/approve
/lgtm

For others
/hold

**Comment by upodroid** [comment]
+1

**Pull request merged**
