### PR TITLE
:broom: Removal of vendor and third-party license dirs

### PR DESCRIPTION
**Pull request by cardil**
## Changes

 - :broom: Removal of vendor and third-party license dirs

/kind cleanup

### CODE REVIEW

**Comment by cardil** [comment]
Review dog is failing some checks because the of how big the diff is

**Review by upodroid — APPROVED** [review]
LGTM

**Comment by cardil** [comment]
/override Do Not Submit
/override style / Golang / Do Not Submit

**Comment by cardil** [comment]
/override "style / Golang / Do Not Submit"

**Pull request merged**
